name: Manual AutoRclone
on: push

jobs:
  build:
    name: My Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Install requirements
      run: pip3 install -r requirements.txt
    - name: Run Auto Rclone
      run: python3 run.py -s 1RrndkL2vYOVmq_ye8sRQymgTFBtR3Hqq -d 0AJ3N5U56HkZoUk9PVA -dp /mySeries -b 1 -e 600 -sa accounts

