name: Manual AutoRclone
on: push

jobs:
  build:
    name: My Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Python test
      run: |
        python3 --version
        python3 -m pip
        pip3

