name: Manual AutoRclone
on: push

jobs:
  build:
    name: My Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Install requirements
      run: pip3 install -r requirements.txt
    - name: Run Auto Rclone
      run: python3 rclone_sa_magic.py -h

